### ISSUE TITLE
Abnormal under multi-GPU configuration.

### ISSUE THREAD

**Issue by nowbug** [danielsyahputra/yolo_distillation#4]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

device=[0, 1, 2, 3, 4, 5, 6, 7] 
[rank2]:     for k, v in self.teacher.named_parameters():
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: AttributeError: 'str' object has no attribute 'named_parameters'

### Environment

Ultralytics 8.3.24 🚀 Python-3.11.10 torch-2.5.1 

### Minimal Reproducible Example

device=[0, 1, 2, 3, 4, 5, 6, 7] 
[rank2]:     for k, v in self.teacher.named_parameters():
[rank2]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank2]: AttributeError: 'str' object has no attribute 'named_parameters'

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Stephen-Hao** [comment]
Hello! I also encountered this issue during multi-GPU training. Have you resolved it?

**Comment by Stephen-Hao** [comment]
你好！我在多卡训练中也遇到这个问题了，请问你解决了吗
